### ISSUE TITLE
Enchanted books from the disenchanter not usable

### ISSUE THREAD

**Issue by LeXiGoD** [Flytre/Mechanix#13]
as the title said the dis enchanter work well but i can't use the enchanted books anymore

from what i can get it's because the books have different NBT tags : vanilla minecraft is "StoredEnchantement"  but the one that comes out is "Enchantement" 

here is a pic of the nbt tags and one of the issue

![2021-03-27_18 29 18](https://user-images.githubusercontent.com/23462375/112729128-ea770880-8f2a-11eb-8e7f-3f2cf191ec83.png)
![2021-03-27_18 32 44](https://user-images.githubusercontent.com/23462375/112729131-eb0f9f00-8f2a-11eb-86e4-0030b76160a6.png)
![2021-03-27_18 32 53](https://user-images.githubusercontent.com/23462375/112729132-eba83580-8f2a-11eb-9cba-6b14d5f4a5c2.png)

**Comment by Flytre** [comment]
Fixed in 5.0.0
