### ISSUE TITLE
Experience Bank bugged

### ISSUE THREAD

**Issue by ZenoMetal** [Flytre/Mechanix#9]
Hi, I just realized, that the XP Bank is nit working as intended. Whenever you store your XP, one Level gets removed from you and you cam then withdraw it and increase your level since it does not take more than one level on depositing XP.
Also the bar is not working as intended I guess. 
![image](https://user-images.githubusercontent.com/77664414/106269362-b2a25c00-622c-11eb-82fc-79fa8a660752.png)

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/106269881-6ad00480-622d-11eb-82ba-4a884b4300b7.png)
I have an other issue with it. It shows I have 0 XP.

**Comment by ZenoMetal** [comment]
Oh, and also I can't get it to put the XP into a Tank with a pipe

**Comment by Flytre** [comment]
Fixed in v5.0.0
